//WIP
/*

using Mirror;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SenderArraySegmentToClients : NetworkBehaviour
{
    private byte[] _data = new byte[100_000_000];
    private uint _dataCount = 0;


    protected Dictionary<int, uint> _clientsConfirmedRecievedDataCount = new Dictionary<int, uint>();


    [Command(requiresAuthority = false)]
    protected void CmdClientRecievedTotal(uint clientDataCount, NetworkConnectionToClient sender = null)
    {
        if (sender == null)
            throw new System.NullReferenceException($"{nameof(sender)} should be generated by Mirror and never be null");

        uint wasConfirmedCount = _clientsConfirmedRecievedDataCount[sender.connectionId];
        if (wasConfirmedCount >= clientDataCount)
            throw new System.Exception($"Client before had already {wasConfirmedCount} but new number should be bigger {clientDataCount}");
        if (clientDataCount > _dataCount)
            throw new System.Exception($"Client can never have more data {clientDataCount} than server {_dataCount}");

        _clientsConfirmedRecievedDataCount[sender.connectionId] = clientDataCount;

        if (clientDataCount < _dataCount)
            SendMoreDataForClient(sender, clientDataCount);
    }

    private void SendMoreDataForClient(NetworkConnectionToClient sender, uint clientDataCount)
    {
        uint needToSendUnchunked = _dataCount - clientDataCount;
        if (needToSendUnchunked == 0)
        {
            throw new System.Exception($"Why this method was called for {sender.connectionId}, data difference is 0");
            //return;
        }

        if (needToSendUnchunked < 0)
            throw new System.Exception($"for client: {sender.connectionId} there is negative number of data that need to be sent: {needToSendUnchunked}, this should never happen");



        throw new NotImplementedException();
    }

    [Command(requiresAuthority = false)]
    protected void CmdCliendConfirmedReceivedDataOnServer(long lastCount, NetworkConnectionToClient sender = null)
    {
        if (sender == null)
            throw new System.NullReferenceException($"{nameof(sender)} should be generated by Mirror and never be null");

        Debug.Log($"CmdOnServer called from {sender.connectionId}");

        CommandCodeOnServer(sender);
    }

    protected override void OnServerWhenClientConnect(NetworkConnectionToClient conn)
    {
        _clientsReady[conn.connectionId] = false;
    }

    public override void OnStartServer()
    {
        NetworkManagerCallbacks.OnServerWhenClientConnect += OnServerWhenClientConnect;
        NetworkManagerCallbacks.OnServerWhenClientDisconnect += OnServerWhenClientDisconnect;
        _serverRunning = true;
    }

    public override void OnStopServer()
    {
        if (_serverRunning == false)
            return;

        NetworkManagerCallbacks.OnServerWhenClientConnect -= OnServerWhenClientConnect;
        NetworkManagerCallbacks.OnServerWhenClientDisconnect -= OnServerWhenClientDisconnect;
        _serverRunning = false;
    }

}

*/